services:
  - type: web
    name: ak88-lotto
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
